spring:
  datasource:
    url: jdbc:mysql://49.232.232.173:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT%2B8
    password: wzy1gqqbuu
  redis:
    host: 49.232.232.173
    port: 6379
    database: 0
    password: wzy1gqqbuu